name: quick_button
description: A package that provides multiple customizable buttons for quick use.
version: 0.1.0
homepage: https://github.com/pozadkey/quick-button
repository: https://github.com/pozadkey/quick-button

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

