name: quick_button
description: A customizable button widget for Flutter applications that allows you to easily create buttons with various attributes and behaviors.
version: 1.0.0
homepage: https://github.com/pozadkey/quick_button
repository: https://github.com/pozadkey/quick_button

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

